FROM docker.io/ocaml/opam:debian-12-ocaml-5.3

ARG http_proxy
ARG https_proxy
ARG no_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

USER root
RUN apt-get update \
    && apt-get install --yes --no-install-recommends git python3 time \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
COPY . .
RUN rm -rf implementations/ocaml/_build \
    && chown -R opam:opam /work

USER opam
RUN opam install --yes \
    astring.0.8.5 bos.0.3.0 cmdliner.1.3.0 dune.3.23.1 fpath.0.7.3 \
    ptime.1.2.0 rresult.0.7.0 yojson.3.0.0
RUN cd implementations/ocaml \
    && opam exec -- dune build --display quiet src/main.exe \
    && opam exec -- dune runtest --display quiet

CMD ["python3", "harness/conformance.py", "--candidate", "ocaml", "--require", "ocaml"]
